apiVersion: v1
kind: Service
metadata:
  name: rag-api-service
  namespace: rag-system
  labels:
    app: rag-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
<<<<<<< HEAD
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8000
    protocol: TCP
    name: https
  selector:
    app: rag-api
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
=======
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: rag-api
  externalTrafficPolicy: Cluster
>>>>>>> 2f0c52b (first commit)
