{{- if .Values.secrets.groqApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rag-chart.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rag-chart.labels" . | nindent 4 }}
type: Opaque
data:
  groq-api-key: {{ .Values.secrets.groqApiKey | b64enc | quote }}
  langsmith-api-key: {{ .Values.secrets.langsmithApiKey | b64enc | quote }}
{{- end }}